x=float(input("enter any number"))

print("your answer in Meter:", x*1000)
print("your answer in Kilometer:", x/1000)
print("your answer in Centimeter:", x*2.54)
print("your answer in Inche :", x/2.54)
print("your answer in Meter:", x*0.3048)
print("your answer in Feet:", x/0.3048)
print("your answer in Kiilometer:", x*1.60934)
print("your answer in Miles:", x/1.60934)